//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetTheGame.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetTheGame.Resources.Resources-fr", typeof(Resources_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a déjà un set !.
        /// </summary>
        internal static string AlreadyASet {
            get {
                return ResourceManager.GetString("AlreadyASet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une autre carte.
        /// </summary>
        internal static string AskButtonText {
            get {
                return ResourceManager.GetString("AskButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donnez une réponse.
        /// </summary>
        internal static string CheatButtonText {
            get {
                return ResourceManager.GetString("CheatButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un mode de jeu.
        /// </summary>
        internal static string ChoseAGamemodeText {
            get {
                return ResourceManager.GetString("ChoseAGamemodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez un classement .
        /// </summary>
        internal static string ChoseLeaderboard {
            get {
                return ResourceManager.GetString("ChoseLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez ici !.
        /// </summary>
        internal static string ClickHereButton {
            get {
                return ResourceManager.GetString("ClickHereButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&apos;accord !.
        /// </summary>
        internal static string CloseRules {
            get {
                return ResourceManager.GetString("CloseRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonyme.
        /// </summary>
        internal static string DefaultUsername {
            get {
                return ResourceManager.GetString("DefaultUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facile.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrez votre pseudo.
        /// </summary>
        internal static string EnterUsernameText {
            get {
                return ResourceManager.GetString("EnterUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez choisir un mode de jeu.
        /// </summary>
        internal static string ErrorNoSelectedText {
            get {
                return ResourceManager.GetString("ErrorNoSelectedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur : aucun mode sélectionné.
        /// </summary>
        internal static string ErrorNoSelectedTitle {
            get {
                return ResourceManager.GetString("ErrorNoSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le but de la &quot;Course au score&quot; est de gagner un maximum de points en un temps donné de votre choix, pouvant varier de 2 à 15 minutes.
        ///
        ///Le but de la &quot;Course au temps&quot; est de donner des bonnes réponses le plus rapidement possible afin d&apos;écouler l&apos;intégralité du paquet en un minimum de temps..
        /// </summary>
        internal static string GamemodeHelpButtonText {
            get {
                return ResourceManager.GetString("GamemodeHelpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présentation des modes de jeu :.
        /// </summary>
        internal static string GamemodeHelpButtonTitle {
            get {
                return ResourceManager.GetString("GamemodeHelpButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course au temps.
        /// </summary>
        internal static string GamemodePickerAgainstScore {
            get {
                return ResourceManager.GetString("GamemodePickerAgainstScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course au score.
        /// </summary>
        internal static string GamemodePickerAgainstTime {
            get {
                return ResourceManager.GetString("GamemodePickerAgainstTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Règles du jeu.
        /// </summary>
        internal static string GameRulesAnnoncement {
            get {
                return ResourceManager.GetString("GameRulesAnnoncement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  a obtenu .
        /// </summary>
        internal static string Got {
            get {
                return ResourceManager.GetString("Got", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficile.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuto HyperSET.
        /// </summary>
        internal static string HypersetTutorial {
            get {
                return ResourceManager.GetString("HypersetTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&apos;après vous, ces 4 cartes forment-elles un HyperSET ? N&apos;hésitez pas à prendre votre temps pour répondre !.
        /// </summary>
        internal static string HypersetTutorialHypersetQuestion {
            get {
                return ResourceManager.GetString("HypersetTutorialHypersetQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Félicitations ! Vous avez terminé le tutoriel d&apos;HyperSET !
        ///
        ///Nous allons à présent lancer une partie d&apos;HyperSET en mode débutant. Dans ce mode débutant, vous aurez la possibilité de tricher, c&apos;est-à-dire de demander une réponse au jeu. Nous vous conseillons de prendre votre temps afin d&apos;analyser pourquoi la réponse est valide..
        /// </summary>
        internal static string HypersetTutorialPageFive {
            get {
                return ResourceManager.GetString("HypersetTutorialPageFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plusieurs HyperSET se sont cachés parmi les 9 cartes suivantes. Saurez-vous en retrouver un ? .
        /// </summary>
        internal static string HypersetTutorialPageFourPartOne {
            get {
                return ResourceManager.GetString("HypersetTutorialPageFourPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bien joué, vous avez trouvé un HyperSET !.
        /// </summary>
        internal static string HypersetTutorialPageFourPartTwo {
            get {
                return ResourceManager.GetString("HypersetTutorialPageFourPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans le tutoriel d&apos;HyperSET ! 
        ///
        ///Si vous voulez apprendre à jouer en HyperSET, il est impératif de savoir jouer à SET. Si vous n&apos;êtes pas encore familier avec SET, nous vous invitons donc à vous entraîner à jouer dans ce mode de jeu. Si vous ne connaissez pas du tout SET, nous vous suggérons de jouer au tutoriel de SET et de vous entraîner jusqu&apos;à être à l&apos;aise..
        /// </summary>
        internal static string HypersetTutorialPageOnePartOne {
            get {
                return ResourceManager.GetString("HypersetTutorialPageOnePartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;HyperSET se joue avec un jeu de 81 cartes identiques au jeu SET : trois couleurs différentes, trois formes différentes, trois remplissages différents et trois nombres différents..
        /// </summary>
        internal static string HypersetTutorialPageOnePartTwo {
            get {
                return ResourceManager.GetString("HypersetTutorialPageOnePartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonne réponse ! Les 4 cartes forment bien un HyperSET comme indiqué ci-dessous..
        /// </summary>
        internal static string HypersetTutorialPageThreePartOneCorrectRight {
            get {
                return ResourceManager.GetString("HypersetTutorialPageThreePartOneCorrectRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvaise réponse ! Les 4 cartes ci-dessus forment un HyperSET comme indiqué ci-dessous. .
        /// </summary>
        internal static string HypersetTutorialPageThreePartOneCorrectWrong {
            get {
                return ResourceManager.GetString("HypersetTutorialPageThreePartOneCorrectWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonne réponse ! Il n&apos;existe aucune carte fantôme pouvant compléter ces 4 cartes..
        /// </summary>
        internal static string HypersetTutorialPageThreePartOneIncorrectRight {
            get {
                return ResourceManager.GetString("HypersetTutorialPageThreePartOneIncorrectRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvaise réponse ! Ces 4 cartes ne forment pas d&apos;HyperSET !.
        /// </summary>
        internal static string HypersetTutorialPageThreePartOneIncorrectWrong {
            get {
                return ResourceManager.GetString("HypersetTutorialPageThreePartOneIncorrectWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonne réponse ! Les 4 cartes ci-dessus forment bien un HyperSET ! Les détails sont affichés ci-dessous..
        /// </summary>
        internal static string HypersetTutorialPageThreePartOneRight {
            get {
                return ResourceManager.GetString("HypersetTutorialPageThreePartOneRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les deux cartes de gauche forment un SET avec la carte centrale. De même, les cartes de droite forment un SET avec la carte centrale. Les 4 cartes (les deux cartes de gauche et les deux cartes de droite) forment donc un HyperSET, et la carte centrale est la Carte fantôme..
        /// </summary>
        internal static string HypersetTutorialPageThreePartTwoRight {
            get {
                return ResourceManager.GetString("HypersetTutorialPageThreePartTwoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un HyperSET est constitué de 4 cartes. Ces 4 cartes, mises deux à deux, doivent former deux SET si on les complète par une même carte. Cette carte n&apos;est pas obligatoirement sur le plateau et est dite &quot;Carte fantôme&quot;..
        /// </summary>
        internal static string HypersetTutorialPageTwoPartOne {
            get {
                return ResourceManager.GetString("HypersetTutorialPageTwoPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les cartes ont été divisées en deux groupes de deux. En cliquant sur le bouton ci-dessous, une cinquième carte va apparaitre : il s&apos;agit de la Carte fantôme. Cette carte forme un SET avec les deux cartes de gauche, et en forme un autre avec les deux cartes de droite. Les 4 cartes forment donc un HyperSET..
        /// </summary>
        internal static string HypersetTutorialPageTwoPartThree {
            get {
                return ResourceManager.GetString("HypersetTutorialPageTwoPartThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les 4 cartes ci-dessus forment un HyperSET. Détaillons cela :.
        /// </summary>
        internal static string HypersetTutorialPageTwoPartTwo {
            get {
                return ResourceManager.GetString("HypersetTutorialPageTwoPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en .
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez sur le texte ci-contre afin de choisir un type de classement..
        /// </summary>
        internal static string LeaderboardAlertText {
            get {
                return ResourceManager.GetString("LeaderboardAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes !.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page suivante.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus aucune carte.
        /// </summary>
        internal static string NoMoreCardsText {
            get {
                return ResourceManager.GetString("NoMoreCardsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun score n&apos;a encore été enregistré pour ce mode de jeu..
        /// </summary>
        internal static string NoScore {
            get {
                return ResourceManager.GetString("NoScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de sets disponibles : .
        /// </summary>
        internal static string NumberOfSetsAvailableText {
            get {
                return ResourceManager.GetString("NumberOfSetsAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouer.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joueur.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  points .
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page précédente.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps restant : .
        /// </summary>
        internal static string RemainingTimeText {
            get {
                return ResourceManager.GetString("RemainingTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réessayer.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre score est : .
        /// </summary>
        internal static string ScoreLabelText {
            get {
                return ResourceManager.GetString("ScoreLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score par minute.
        /// </summary>
        internal static string ScorePerMinute {
            get {
                return ResourceManager.GetString("ScorePerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  secondes..
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutoriel SET.
        /// </summary>
        internal static string SetTutorial {
            get {
                return ResourceManager.GetString("SetTutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher la carte.
        /// </summary>
        internal static string ShowCard {
            get {
                return ResourceManager.GetString("ShowCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les scores.
        /// </summary>
        internal static string ShowScores {
            get {
                return ResourceManager.GetString("ShowScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer la partie.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temps.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre temps : .
        /// </summary>
        internal static string TimeFromBeginning {
            get {
                return ResourceManager.GetString("TimeFromBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutoriel.
        /// </summary>
        internal static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trois SET se sont cachés parmi les 9 cartes suivantes ! Saurez-vous en retrouver un ?.
        /// </summary>
        internal static string TutorialPageFivePartOne {
            get {
                return ResourceManager.GetString("TutorialPageFivePartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bien joué ! Vous avez trouvé le SET !.
        /// </summary>
        internal static string TutorialPageFivePartTwo {
            get {
                return ResourceManager.GetString("TutorialPageFivePartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les 3 cartes ci-dessus forment-elles un SET ?.
        /// </summary>
        internal static string TutorialPageFourMultipleParts {
            get {
                return ResourceManager.GetString("TutorialPageFourMultipleParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un petit peu de pratique !
        ///
        ///Les 3 cartes suivantes forment-elles un SET ?.
        /// </summary>
        internal static string TutorialPageFourPartOne {
            get {
                return ResourceManager.GetString("TutorialPageFourPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonne réponse ! Les 3 cartes ci-dessus forment bien un SET puisque les 4 critères (forme, couleur, nombre, remplissage) sont tous soit identiques soit différents pour les 3 cartes..
        /// </summary>
        internal static string TutorialPageFourPartThreeRight {
            get {
                return ResourceManager.GetString("TutorialPageFourPartThreeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvaise réponse ! Les 3 cartes ci-dessus forment un SET. En effet, les 4 critères (forme, couleur, nombre et remplissage) sont tous soit identiques soit différents pour les 3 cartes..
        /// </summary>
        internal static string TutorialPageFourPartThreeWrong {
            get {
                return ResourceManager.GetString("TutorialPageFourPartThreeWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonne réponse ! Puisque deux cartes présentent des formes pleines, mais pas la troisième, les 3 cartes ci-dessus ne forment pas un SET..
        /// </summary>
        internal static string TutorialPageFourPartTwoRight {
            get {
                return ResourceManager.GetString("TutorialPageFourPartTwoRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauvaise réponse ! Les 3 cartes-ci dessus ne conviennent pas puisque le remplissage des symboles n&apos;est pas bon. Les 3 cartes ne présentent ni un remplissage strictement identique, ni un remplissage strictement différent..
        /// </summary>
        internal static string TutorialPageFourPartTwoWrong {
            get {
                return ResourceManager.GetString("TutorialPageFourPartTwoWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans le tutoriel de SET !
        ///
        ///Le jeu SET est composé de 81 cartes qui présentent des symboles qui possèdent 4 caractéristiques distinctes :
        ///- Leur forme : ovale, losange, vague
        ///- Leur couleur : Bleu, rouge, vert (modifiables dans les options)
        ///- Leur quantité : Une, deux, trois formes
        ///- Leur remplissage : Plein, vide, hachuré.
        /// </summary>
        internal static string TutorialPageOnePartOne {
            get {
                return ResourceManager.GetString("TutorialPageOnePartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les trois cartes ci-dessus représentent les différents remplissages, formes, couleurs et nombre disponibles.
        ///
        ///Le but du jeu est de trouver le plus rapidement possible des groupes de 3 cartes respectant des critères précis. On appelle ces groupes des SET..
        /// </summary>
        internal static string TutorialPageOnePartTwo {
            get {
                return ResourceManager.GetString("TutorialPageOnePartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Félicitations ! Vous avez fini le tutoriel de SET !
        ///
        ///Si vous le souhaitez, vous pouvez rejouer le tutoriel dans le menu des options.
        ///
        ///Nous allons à présent lancer une partie de SET en mode débutant. Pendant cette partie, vous aurez la possibilité de &quot;tricher&quot;, c&apos;est-à-dire de cliquer sur un bouton qui vous donnera une réponse. Mais attention, vous perdrez un point si vous le faites !.
        /// </summary>
        internal static string TutorialPageSixPartOne {
            get {
                return ResourceManager.GetString("TutorialPageSixPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deux autres exemples :.
        /// </summary>
        internal static string TutorialPageThreePartOne {
            get {
                return ResourceManager.GetString("TutorialPageThreePartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les 3 cartes ci-dessus, quant à elles, ne forment pas un SET. Elles vérifient certains critères :
        ///- Les 3 cartes présentent le même nombre
        ///- Les 3 cartes présentent des couleurs différentes
        ///- Les 3 cartes présentent un remplissage différent
        ///Mais elles ne valident pas le critère de la forme ! En effet, deux d&apos;entre elles présentent une forme en losange, mais pas la troisième..
        /// </summary>
        internal static string TutorialPageThreePartThree {
            get {
                return ResourceManager.GetString("TutorialPageThreePartThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les 3 cartes ci-dessus forment un SET puisque :
        ///- Les 3 cartes ont la même forme
        ///- Les 3 cartes ont un nombre différent
        ///- Les 3 cartes ont un remplissage différent
        ///- Les 3 cartes ont les mêmes couleurs.
        /// </summary>
        internal static string TutorialPageThreePartTwo {
            get {
                return ResourceManager.GetString("TutorialPageThreePartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un SET est un ensemble de 3 cartes dont chacune des 4 caractéristiques est soit totalement identique, soit totalement différente des deux autres cartes.
        ///Trois cartes forment donc un SET si et seulement si les 4 règles suivantes sont respectées :
        ///- La couleur des symboles est 3 fois strictement identique ou 3 fois totalement différente;
        ///- La forme des symboles est 3 fois strictement identique ou 3 fois totalement différente;
        ///- Le nombre de symboles est 3 fois strictement identique ou 3 fois totalement di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TutorialPageTwoPartOne {
            get {
                return ResourceManager.GetString("TutorialPageTwoPartOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les trois cartes ci-dessus forment un SET. Détaillons les 4 critères présentés si dessus :
        ///
        ///- Les 3 cartes présentent une forme identique : ✔
        ///- Les 3 cartes présentent des couleurs différentes : ✔
        ///- Les 3 cartes présentent un nombre différent : ✔
        ///- Les 3 cartes présentent un remplissage différent : ✔.
        /// </summary>
        internal static string TutorialPageTwoPartTwo {
            get {
                return ResourceManager.GetString("TutorialPageTwoPartTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pseudo.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez vous lancer le tutoriel ?.
        /// </summary>
        internal static string WantATutorial {
            get {
                return ResourceManager.GetString("WantATutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez obtenu .
        /// </summary>
        internal static string YourScoreText {
            get {
                return ResourceManager.GetString("YourScoreText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez réussi en .
        /// </summary>
        internal static string YourTimeText {
            get {
                return ResourceManager.GetString("YourTimeText", resourceCulture);
            }
        }
    }
}
